query myEvent($relativePath: String!) {
  event(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
      _values
    }
    ...MyEventParts
  }
}

fragment MyEventParts on Event {
  __typename
  events {
    __typename
    title
    institution
    type
    date
    time
    location
    description
    href
  }
}
