query myFooter($relativePath: String!) {
  footer(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
      _values
    }
    ...MyFooterParts
  }
}

fragment MyFooterParts on Footer {
  __typename
  name
  email
  address
  footerLinks {
    __typename
    href
    text
  }
}
