query myHomePage($relativePath: String!) {
  homePage(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
      _values
    }
    ...MyHomePageParts
  }
}

fragment MyHomePageParts on HomePage {
  __typename
  head {
    __typename
    title
    description
  }
  h1
  subtitle
  body
}
