query myPublication($relativePath: String!) {
  publication(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
      _values
    }
    ...MyPublicationParts
  }
}

fragment MyPublicationParts on Publication {
  __typename
  publications {
    __typename
    citation
    category {
      ... on PublicationCategory {
        __typename
        name
      }
      ... on Document {
        _sys {
          filename
          basename
          hasReferences
          breadcrumbs
          path
          relativePath
          extension
        }
        id
      }
    }
    img
    href
    featured
  }
}
